# Generated by Django 3.1.3 on 2021-04-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_reports',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
