# Generated by Django 3.1.3 on 2021-04-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_num_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='num_reports',
        ),
    ]
