# Generated by Django 3.1.3 on 2021-04-11 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reporte.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHumedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numAsignado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('celular', models.IntegerField()),
                ('correoElectronico', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='reporte_pics')),
                ('humedal', models.CharField(choices=[('1', 'La Babilla'), ('2', 'El Retiro'), ('3', 'Ecoparque Las Garzas')], max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Humedales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('areaEstacional', models.FloatField()),
                ('areaPermanente', models.FloatField()),
                ('latitud', models.FloatField()),
                ('altitud', models.FloatField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.comuna')),
                ('tipoHumedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.tipohumedal')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[reporte.models.validate_image], verbose_name='Image')),
                ('descripcion', models.TextField()),
                ('status', models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], max_length=200)),
                ('importancia', models.CharField(choices=[('Muy Importante', 'Muy Importante'), ('Regular', 'Regular')], max_length=200)),
                ('nombreHumedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.humedales')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.usuario')),
                ('tipoAporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.tipoaporte')),
            ],
        ),
    ]
