# Generated by Django 3.1.7 on 2021-04-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHumedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numAsignado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Humedales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('areaEstacional', models.FloatField()),
                ('areaPermanente', models.FloatField()),
                ('latitud', models.FloatField()),
                ('altitud', models.FloatField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.comuna')),
                ('tipoHumedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.tipohumedal')),
            ],
        ),
    ]
