# Generated by Django 3.1.7 on 2021-04-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='humedales',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipohumedal',
            old_name='name',
            new_name='nombre',
        ),
    ]
