# Generated by Django 3.1.7 on 2021-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faunaacuatica',
            name='foto',
            field=models.ImageField(upload_to='faunaAcuatica/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='faunaterrestre',
            name='foto',
            field=models.ImageField(upload_to='faunaTerrestre/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='foto',
            field=models.ImageField(upload_to='flora/', verbose_name='Image'),
        ),
    ]
