# Generated by Django 3.1.3 on 2021-04-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='nombreHumedal',
            new_name='humedal',
        ),
    ]
