# Generated by Django 3.1.3 on 2021-04-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_auto_20210416_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='importancia',
            field=models.CharField(choices=[('Muy Importante', 'Muy Importante'), ('Regular', 'Regular')], default='Regular', max_length=200),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='status',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], default='Invisible', max_length=200),
        ),
    ]
