# Generated by Django 3.1.7 on 2021-04-03 19:33

from django.db import migrations, models
import django.db.models.deletion
import reporte.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_auto_20210403_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('celular', models.IntegerField()),
                ('correoElectronico', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='uploads/', validators=[reporte.models.validate_image], verbose_name='Image')),
                ('descripcion', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], max_length=200)),
                ('importancia', models.CharField(choices=[('Muy Importante', 'Muy Importante'), ('Regular', 'Regular')], max_length=200)),
                ('nombreHumedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.humedales')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.usuario')),
                ('tipoAporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.tipoaporte')),
            ],
        ),
    ]
