# Generated by Django 3.1.3 on 2021-04-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_reporte_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='humedal',
            field=models.CharField(choices=[('1', 'La Babilla'), ('2', 'El Retiro'), ('3', 'Ecoparque Las Garzas')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='reporte_pics'),
        ),
    ]
