# Generated by Django 3.1.3 on 2021-08-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_auto_20210416_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='labels',
            field=models.JSONField(default='{}'),
        ),
    ]
