# Generated by Django 3.1.3 on 2021-08-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0004_reporte_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='labels',
            field=models.JSONField(default=dict),
        ),
    ]
