# Generated by Django 3.1.3 on 2021-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0006_auto_20211030_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humedal',
            old_name='altitud',
            new_name='areatotalhumedal',
        ),
        migrations.RenameField(
            model_name='humedal',
            old_name='areaEstacional',
            new_name='cuerpodeagua',
        ),
        migrations.RenameField(
            model_name='humedal',
            old_name='areaPermanente',
            new_name='franjaforestalprotectora',
        ),
        migrations.RemoveField(
            model_name='humedal',
            name='latitud',
        ),
    ]
