# Generated by Django 3.1.3 on 2021-10-30 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0009_auto_20211030_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humedal',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('/[A-Za-z\\d\\s]/g', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
