# Generated by Django 3.1.3 on 2021-10-30 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0011_auto_20211030_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humedal',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$/', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
